name: Package build

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          submodules: recursive

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v0.6.0
        with:
          version: "latest"

      - name: Generate protobuf files
        run: make generate

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with Maven (package)
        run: make package

      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: mvn --settings settings.xml --file pom.xml deploy -DskipTests