package com.xignite.sdk.api.webservices.XigniteGlobalMaster.Models;

public enum InstrumentClasses {
   BOND,
   INDICES,
   STOCK,
   OTHER,
   STRUCTUREDPRODUCT,
   FUND,
   MONEYMARKET,
   DERIVATIVE,
   CURRENCY,
   TECHNICAL,
   COMMODITY,
   CURRENCYFORWARD,
   INTERESTRATESWAPS,
   DEPOSITORYRECEIPT,
   EXCHANGETRADEDFUND,
   PREFERREDSHARES,
   COVEREDWARRANT,
   WARRANT,
   UNITS,
   EXCHANGETRADEDCOMMODITY,
   ALL;
}
