package com.xignite.sdk.api.webservices.XigniteRates.Models;

public enum FederalRateTypes {
   PRIMARYBOSTON,
   PRIMARYNEWYORK,
   PRIMARYPHILADELPHIA,
   PRIMARYCLEVELAND,
   PRIMARYRICHMOND,
   PRIMARYATLANTA,
   PRIMARYCHICAGO,
   PRIMARYSTLOUIS,
   PRIMARYMINNEAPOLIS,
   PRIMARYKANSASCITY,
   PRIMARYDALLAS,
   PRIMARYSANFRANCISCO,
   SECONDARYBOSTON,
   SECONDARYNEWYORK,
   SECONDARYPHILADELPHIA,
   SECONDARYCLEVELAND,
   SECONDARYRICHMOND,
   SECONDARYATLANTA,
   SECONDARYCHICAGO,
   SECONDARYSTLOUIS,
   SECONDARYMINNEAPOLIS,
   SECONDARYKANSASCITY,
   SECONDARYDALLAS,
   SECONDARYSANFRANCISCO;
}
