package com.xignite.sdk.api.webservices.XigniteEstimates.Models;

public enum EstimatesResearchReportTypes {
   EARNINGSESTIMATES,
   ESTIMATESRECOMMENDATIONS,
   YAHOOFINANCEESTIMATES,
   EARNINGSSURPRISE,
   ANALYSTRECOMMENDATIONS,
   ANALYSTRECOMMENDATIONSANDHISTOGRAM,
   SECTORANALYSIS,
   EPSGROWTHRATES,
   EARNINGSESTIMATESCONSENSUSTREND,
   DEFAULT;
}
