package com.xignite.sdk.api.webservices.XigniteAnalysts.Models;

public enum AnalysisGroups {
   ANALYSTRECOMMENDATIONS,
   ANALYSTRECOMMENDATIONSANDHISTOGRAM,
   CURRENTSALESCONSENSUS,
   CURRENTSALESCONSENSUSCHANGE,
   SUMMARYCURRENTSTATISTICS,
   SUMMARYCURRENTSTATISTICSCHANGE,
   ALL;
}
