package com.xignite.sdk.api.webservices.XigniteInsider.Models;

public enum TransactionCodes {
   ALL,
   PURCHASE,
   SALE,
   TRANSACTIONREPORTEDEARLY,
   NQSOGRANT,
   NQSODISPOSITION,
   NQSOSAMEDAYEXERCISE,
   NQSODISCRETIONARYTRANSACTION,
   NQSOEXERCISE,
   CONVERSION,
   EXPIRATIONOFSHORTPOSITION,
   EXPIRATIONOFLONGPOSITION,
   EXERCISEOUTOFTHEMONEY,
   EXERCICEINTHEMONEY,
   BONAFIDEGIFT,
   SMALLACQUISITION,
   ACQUISITIONORDISPOSITIONBYWILL,
   DEPOSITORWITHDRAWALFROMTRUST,
   OTHERACQUISITIONORDISPOSITION,
   SWAP,
   DISPOSITIONOFTENDER,
   NONE;
}
