name: Maven Package

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_PAT }}
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with Maven (package)
        run: make package

      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        run: mvn --settings settings.xml --file pom.xml deploy -DskipTests