name: Maven Package

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        type: choice
        description: Environment
        required: true
        options:
          - run

jobs:
  test:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Copy settings.xml
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        run: cp $GITHUB_WORKSPACE/settings.xml $HOME/.m2/settings.xml

      - name: Build with Maven (package)
        run: mvn clean package spring-boot:repackage -DskipTests

      - name: Deploy to Github Package Registry
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "GITHUB_ACTOR: $GITHUB_ACTOR"
          echo "GITHUB_SHA: $GITHUB_SHA"
          echo "GITHUB_USERNAME: $GITHUB_USERNAME"
          echo "GITHUB_TOKEN: $GITHUB_TOKEN"
          mvn deploy -DskipTests