name: Maven Package

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        type: choice
        description: Environment
        required: true
        options:
          - run

jobs:
  test:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_PAT }}
          submodules: recursive

      - name: Build with Maven (package)
        run: mvn clean package spring-boot:repackage -DskipTests

      - name: Publish to GitHub Packages Apache Maven
        env:
          GITHUB_USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        run: mvn --settings settings.xml --file pom.xml deploy -DskipTests